### ISSUE TITLE
Nextcloud 27.0.2: Erstellung der eID-Verknüpfung fehlgeschlagen! Bitte stellen Sie sicher, dass die genutzte eID-Karte gültig ist.✖

### ISSUE THREAD

**Issue by dr-br** [eid-login/eid-login-nextcloud#14]
eID Verknüpfung schlägt fehl.
Die Settings entsprechen denen in #11 beschriebenen.
Einziger (mir ersichtlicher) Unterschied: NC 27 statt 24.
Den genauen Zeitpunkt, ab welcher Version eID nicht mehr funktioniert, kenne ich nicht.

**Comment by ecmrauh** [comment]
Ich konnte das Problem nachstellen. Es tritt erst seit Nextcloud 27.0.1 auf, unabhängig von der Version des eidlogin-Plugins (getestet mit 1.0.12 und der aktuellen 1.0.13). Frühere Versionen bis hin zu Version 27.0.0 funktionieren.

Die Ursache ist die neue Funktion `libxml_set_external_entity_loader` im Commit https://github.com/nextcloud/server/commit/227497705e03758fef0816b55d841d47044a4f37. Kommentiert man diese drei Zeilen aus, geht es wieder.

Als nächstes werde ich schauen, ob ich etwas in unserem Plugin ändern kann / muss oder ob das Problem direkt in Nextcloud behoben werden muss.

**Comment by dr-br** [comment]
Danke für die schnelle Rückmeldung!

**Comment by ecmrauh** [comment]
Ich habe eine Lösung bei der [Nextcloud SAML App](https://github.com/nextcloud/user_saml) gefunden (siehe https://github.com/eid-login/eid-login-nextcloud/commit/fef9891fb1fe01a23aad0a9366143f4721de882b), die zumindest mit Nextcloud 27 und PHP 8.2 funktioniert. Nach abschließenden Tests mit anderen Nextcloud- und PHP-Versionen wird es eine neue Version dieses Plugins geben, die das Problem beheben sollte.

**Comment by ecmrauh** [comment]
Die [Version 1.0.14](https://github.com/eid-login/eid-login-nextcloud/releases/tag/1.0.14) unseres Plugins wurde soeben veröffentlicht. Dadurch sollte eine eID-Verknüpfung wieder möglich sein, auch mit der aktuellsten Nextcloud-Version.

**Comment by dr-br** [comment]
Funktioniert einwandfrei. Danke!
