### ISSUE TITLE
Setup for SkIdentity fails

### ISSUE THREAD

**Issue by tuxmaster** [eid-login/eid-login-nextcloud#15]
Using the SkIdentity service which comes with the add on fails.
When I press on "Weiter mit SkiIdentity" nothing happens.
In the browser console I see this error:
```
[HTTP/2 422 Unprocessable Entity 343ms]
for the url:
https://myServer/apps/eidlogin/settings/fetchidp/aHR0cHMlM0ElMkYlMkZzZXJ2aWNlLnNraWRlbnRpdHkuZGUlMkZmcyUyRnNhbWwlMkZtZXRhZGF0YQ==
```
In the sever log I see this:

> Nextcloud[176210]: {"reqId":"ZOB3JLR2mywQ-CUUtk8BmQAAxyA","level":1,"time":"2023-08-19T10:02:44+02:00","remoteAddr":"<ClientIP>","user":"<User>","app":"eidlogin","method":"GET","url":"/apps/eidlogin/settings/fetchidp/aHR0cHMlM0ElMkYlMkZzZXJ2aWNlLnNraWRlbnRpdHkuZGUlMkZmcyUyRnNhbWwlMkZtZXRhZGF0YQ==","message":"Error on parseRemoteXML. error:0A000410:SSL routines::sslv3 alert handshake failure","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/116.0","version":"25.0.10.1","data":{"app":"eidlogin"}}

It looks like service.skidentity.de don't support TLS1.3.
SSLabs will confirm this. So the AddOn is very useless, when the default provider don's support TLS1.3, because TLS1.2 is susceptible for the D(HE)ater attack. So using of TLS1.2 will be an big problem, because the secure curves(Curve25519 and Ed448) are only standardized for TLS1.3.

**Comment by ecmrauh** [comment]
Thanks for reporting the issue. TLS 1.3 support is coming soon.

**Comment by sake** [comment]
SkIDentity TLS config has been updated to allow TLS 1.3.

**Comment by tuxmaster5000** [comment]
Hm, it looks like it will not be resolved completely, because it fails from an TLS1.3 only system still:
```
curl -vvv --tlsv1.3 --tls13-ciphers TLS_AES_256_GCM_SHA384 https://service.skidentity.de/fs/saml/metadata
*   Trying 62.128.4.252:443...
* Connected to service.skidentity.de (62.128.4.252) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* TLS 1.3 cipher selection: TLS_AES_256_GCM_SHA384
*  CAfile: /etc/pki/tls/certs/ca-bundle.crt
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS header, Unknown (21):
* TLSv1.3 (IN), TLS alert, handshake failure (552):
* error:0A000410:SSL routines::sslv3 alert handshake failure
* Closing connection 0
curl: (35) error:0A000410:SSL routines::sslv3 alert handshake failure

```

**Comment by ecmrauh** [comment]
Your command above works on my laptop (Debian 12) with the default curl / OpenSSL version (`curl 7.88.1 (x86_64-pc-linux-gnu) libcurl/7.88.1 OpenSSL/3.0.9`). Also `openssl s_client -connect service.skidentity.de:443 -tls1_3 -trace` returns no error. As we don't use an unusual setup for our webserver, I'm afraid there is nothing we can do on our site.

**Comment by tuxmaster5000** [comment]
We don't use Debian for security reasons. We use only RHEL.
The OpenSSL call also fails on RHEL:

> openssl s_client -connect service.skidentity.de:443 -tls1_3 
> CONNECTED(00000003)
> 405C1C5C477F0000:error:0A000410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:ssl/record/rec_layer_s3.c:1600:SSL alert number 40
> ---
> no peer certificate available
> ---
> No client certificate CA names sent
> ---
> SSL handshake has read 7 bytes and written 247 bytes
> Verification: OK
> ---
> New, (NONE), Cipher is (NONE)
> Secure Renegotiation IS NOT supported
> Compression: NONE
> Expansion: NONE
> No ALPN negotiated
> Early data was not sent
> Verify return code: 0 (ok)

**Comment by ecmrauh** [comment]
I tested the OpenSSL call on a Rocky Linux 8.8 VM and it works. Can you provide us the complete output of the following command?

`openssl s_client -connect service.skidentity.de:443 -tls1_3 -trace -debug`

Can you also provide us more information about the system and the software versions you are using?
