### ISSUE TITLE
Der Benutzer existiert nicht oder ist nicht mit eID registriert.

### ISSUE THREAD

**Issue by DanielChristopherLange** [eid-login/eid-login-nextcloud#16]
Hey, 

im trying to register my dog for taxpurposes in the city of Kiel @ https://idp.serviceportal.schleswig-holstein.de

There i can use the Ausweisapp2 to log in, but for some reason it declines my personal details stating the failurenote from the headline.

Please help to identify the problem so i can continue to register my dog.

Thanks & Best Regards,
Daniel

**Comment by ecmrauh** [comment]
I'm afraid, you're wrong here. Or do you have any issues with our Nextcloud plugin?
