### ISSUE TITLE
Does this prevent Multi-Account per Idcard?

### ISSUE THREAD

**Issue by schichtnudelauflauf** [eid-login/eid-login-nextcloud#17]
Can one EId card create multiple accounts?
Can I cross-link them?
What data does SkIdentity see?

**Comment by ecmrauh** [comment]
You can only create one eID per Nextcloud instance, otherwise you get an error ("The eID is already connected to another account"). What SkIDentity sees is only a ["pseudonym"](https://www.personalausweisportal.de/Webs/PA/DE/verwaltung/technik/pseudonym/pseudonym-node.html).

**Comment by schichtnudelauflauf** [comment]
I read this as: The pseudonymous identity depends on the specific accredited endorsement (or whatever 'Berechtigungs-' is translated from) entity's pki identity and the ID-Card itself.
Does it depend on the individual card or the person? What happens to authorization when the owner gets a new card because the old one expired?
So the pseudonymous identity will be the same for everything using this plugin without a custom endorsement entity and I could correlate them between multiple Nextcloud instances?
Or is the requestors identity a part of the pseudonym generator inputs?

**Comment by ecmrauh** [comment]
The pseudonym is calculated from the "Berechtigungszertifikat" of the website and the eID card (not the person). This means, you have to re-assign a new card if the old one expires.

The pseudonym will always be different, except on the same site with the same eID card.

**Comment by schichtnudelauflauf** [comment]
You didn't answer the detail I looked for specifically:

Default conf of this repo, so using SkIdentity.

Is the pseudonym uniqueness granularity per

SkIdentity + Card

or per

Specifc Nextcloud http Origin + SkIdentity + Card
?

Is the http origin the difference or something else?
The docu mentions the plugin doing a self signed cert for registration with SkIdentity. Is that the differentiating thing?

**Comment by ecmrauh** [comment]
The pseudonym is unique per "Specifc Nextcloud http origin + SkIdentity + Card" (as SkIDentity "adds" the uniqueness to the calculation for every origin).

The self signed certificate is used for the communication of the Nextcloud instance with SkIDentity (signing the SAML request) and has nothing to do with the pseudonym.
