### ISSUE TITLE
SMS verification code related

### ISSUE THREAD

**Issue by Jojo007JB** [eid-login/eid-login-nextcloud#20]
Dear Sir/Madame,

I am a Pharmacist and have recently been granted access to the CARE POYC on line system, accessing through eID credentials. Once I log into the Care POYC system, using my eID credentials, I need to in turn receive an SMS confirmatory code, that I need to introduce into the Care POYC system to access. However, I am not receiving the SMD code. I have checked by registered mobile phone within the eID and confirmed that its correct. Appreciate your support/guidance of how I can resolve this matter and access the POYC system.

Thanks & regards,
Joseph.

**Comment by ecmrauh** [comment]
Dear Joseph, I'm afraid you are at the wrong place here. This repository only contains the source code for accessing Nextcloud with the German eID. We are not affiliated with the Care POYC system or anything like that. Sorry.
