### ISSUE TITLE
SKIdentity Error 500 beim Aufruf eID-Login

### ISSUE THREAD

**Issue by Hans1Hansen** [eid-login/eid-login-nextcloud#5]
Sehr geehrte Damen und Herrn,

ich habe bei Nextcloud Version 22 die App für das eID-Login installiert und die Erstkonfiguration m.E. erfolgreich durchgeführt. 
Die Nextcloud-Instanz ist unter der URL https://[meine.adresse]/nextcloud erreichbar, was ich bei der Konfiguration des Service Providers entsprechend eingetragen habe. 

Wenn ich nun aber versuche, einen Account zu verknüpfen, erhalte ich im Webbrowser folgende Fehlermeldung:

Error 500
Failed to process obligation. Reason: Unknown issuer profile (a.k.a. Service entityID) 'https://[meine.adresse]/nextcloud'

Die Situation hat sich auch nach einem Neustart des Servers nicht geändert. 
Ebenso wenig wie einen Versuch mit dem Weglassen von /nextcloud bei der Eingabe der URL für den Service Provider.
Für einen Hinweis wäre ich Ihnen dankbar.

Mit besten Grüßen,

Oskar Leipold

**Comment by 7118path** [comment]
Hallo Herr Leipold,

bitte prüfen Sie, welche EntityID sie bei der Einrichtung des Service Provider bei SkIDentity eingetragen haben.
Dieser Wert scheint nicht korrekt zu sein.

Sie können den vollständigen Prozess der Einrichtung in diesem Screencast ansehen: https://www.youtube.com/watch?v=7a-V-lB_AQ8
Der relevante Abschnitt beginnt bei 1:30

Sollten Sie weiterhin Probleme haben mit der Einrichtung bzw. Nutzung, so würde ich Sie bitten sich per E-Mail an eID-Login@ecsec.de zu wenden, da die Issues hier bei GitHub eher für Probleme mit dem Code der Anwendung gedacht sind.

Vielen Dank und Gruß

Tobias Assmann
